config:
  elicit_expiry: 60

policies:
  - "bf:read_emails:tool_access:allow"
  - "af:read_emails:email_fields:allow:subject"
  - "af:read_emails:email_fields:deny:body"
  - "af:read_emails:email_fields:deny:attachments"
  - "af:read_emails:email_fields:elicit:timestamp"